### ISSUE TITLE
Release to CPAN

### ISSUE THREAD

**Issue by reneeb** [oetiker/mojolicious-plugin-qooxdoo#1]
Hi,

can you release a new version to CPAN? With Mojolicious 5.73 the OO-interface of Mojo::JSON went away and your plugin (version 0.95 on CPAN) starts to fail to install...
- Renée

**Comment by oetiker** [comment]
Hi Renee,
please switch to https://metacpan.org/release/Mojolicious-Plugin-Qooxdoo
the other module is rather un Mojo like ... will release an update with a deprecation notice

**Comment by reneeb** [comment]
Thanks, added the old dist to the blacklist for http://mojo.perl-services.de
